# Generated by Django 5.2.14 on 2026-06-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('plc', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('bldgrp', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('availability', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(default='', max_length=100)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidApp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_coviddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doxray', models.DateField()),
                ('effected', models.CharField(default='', max_length=100)),
                ('symptoms', models.CharField(default='', max_length=100)),
                ('xray_image', models.ImageField(blank=True, null=True, upload_to='xray_image/')),
                ('covid_result', models.CharField(default='', max_length=100)),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidApp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField(default='2023-12-31')),
                ('time', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidApp.tbl_doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidApp.tbl_register')),
            ],
        ),
    ]
