# Generated by Django 5.2.14 on 2026-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_register',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
